<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'alintond_pres1');
define('_DB_USER_', 'alintond_pres1');
define('_DB_PASSWD_', 'TClXRjv2V');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'v1j4e92MIQUCJqWjGXXmTY1chVWMXwhIgCMFxOdieB3D6p3DWdSrPguS');
define('_COOKIE_IV_', '1vGWBJfB');
define('_PS_CREATION_DATE_', '2015-11-07');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'ybtY1JoTUBAgEYmdy9UqAJYEfqEjqGX8');
define('_RIJNDAEL_IV_', 'L0YPxHLp/s+Qpn730uSVZg==');
