<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'alintond_pres1');
define('_DB_USER_', 'alintond_pres1');
define('_DB_PASSWD_', 'TClXRjv2V');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'cgP7zkD0yHSGXp2abMw9QUHyeEbZ9F7iocNiDY7VE1nTbpHSb9yqA4pW');
define('_COOKIE_IV_', 'odYLn2ow');
define('_PS_CREATION_DATE_', '2014-09-12');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'u8h5U4MP6C1bi5fHHMeRbvaxEAtrrMuW');
define('_RIJNDAEL_IV_', 'NUFrkn28cO3flzDuVGsPCQ==');
